### ISSUE TITLE
Thailand

### ISSUE THREAD

**Issue by pich4ya** [fs0c131y/covid19-tracker-apps#6]
MorChana - หมอชนะ : Android Mobile Application ( https://play.google.com/store/apps/details?id=com.thaialert.app )
MorChana - หมอชนะ : iOS Mobile Application ( https://apps.apple.com/th/app/id1505185420 )

Vulnerability Disclosure Policy
https://github.com/codeforpublic/disclosure-policy

**Comment by fs0c131y** [comment]
Fixed by bea656ea0ef3a9c99b24417ed50370c538018e7e
